"""removed nullability

Revision ID: 00199a105370
Revises: 31c8b7a21f54
Create Date: 2025-05-04 11:00:02.268006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00199a105370'
down_revision = '31c8b7a21f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
