"""Allow NULL values for verification_code

Revision ID: 083e53ab107f
Revises: 452d8a5fb683
Create Date: 2025-05-04 10:28:56.916476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '083e53ab107f'
down_revision = '452d8a5fb683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('verification_code',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('verification_code',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)

    # ### end Alembic commands ###
