"""fixed user.py

Revision ID: 241d456eda95
Revises: 4d37cfcdf36d
Create Date: 2025-05-04 08:33:15.303734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241d456eda95'
down_revision = '4d37cfcdf36d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('verification_code', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_code')
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
