"""renamed an attribute

Revision ID: 2b5d4639086c
Revises: 7ef42c931463
Create Date: 2025-05-04 06:34:58.741127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5d4639086c'
down_revision = '7ef42c931463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
