"""Set default value for verification_code

Revision ID: 31c8b7a21f54
Revises: 083e53ab107f
Create Date: 2025-05-04 10:32:03.394177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c8b7a21f54'
down_revision = '083e53ab107f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('verification_code',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('verification_code',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)

    # ### end Alembic commands ###
