"""changed user-attributes

Revision ID: 452d8a5fb683
Revises: 241d456eda95
Create Date: 2025-05-04 10:12:55.263092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452d8a5fb683'
down_revision = '241d456eda95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('verification_code',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
        batch_op.alter_column('two_fa_secret',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('two_fa_secret',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('verification_code',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)

    # ### end Alembic commands ###
