"""removed a verify column

Revision ID: 698611031a14
Revises: 455ea4c21c75
Create Date: 2025-05-03 18:14:31.244117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698611031a14'
down_revision = '455ea4c21c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
