"""added 2tp verification

Revision ID: 7ef42c931463
Revises: 837835b8ac9e
Create Date: 2025-05-04 05:57:58.306010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef42c931463'
down_revision = '837835b8ac9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_2fa_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('two_fa_secret', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('two_fa_secret')
        batch_op.drop_column('is_2fa_enabled')

    # ### end Alembic commands ###
