"""reversed changes

Revision ID: 837835b8ac9e
Revises: 698611031a14
Create Date: 2025-05-03 23:16:19.758415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837835b8ac9e'
down_revision = '698611031a14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_code', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_code')

    # ### end Alembic commands ###
