"""removed attributes

Revision ID: 8b1628c5ee64
Revises: ccd3edf9f7d3
Create Date: 2025-05-11 13:57:07.189181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b1628c5ee64'
down_revision = 'ccd3edf9f7d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('delivery_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_address', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
