"""add_order_item_type_check_constraint

Revision ID: 924ce657b83d
Revises: ca945fed3446
Create Date: 2025-05-12 06:30:45.411831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924ce657b83d'
down_revision = 'ca945fed3446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "ck_order_item_type",
        "order_items",
        "(product_id IS NOT NULL AND service_id IS NULL) OR (product_id IS NULL AND service_id IS NOT NULL)"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_order_item_type", "order_items", type_="check")
    # ### end Alembic commands ###
