"""increased length of string

Revision ID: b843c19b9b2d
Revises: 5034979a60f2
Create Date: 2025-05-04 12:22:47.412462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b843c19b9b2d'
down_revision = '5034979a60f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=10000000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=10000000),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)

    # ### end Alembic commands ###
