"""add_cart_item_type_check_constraint

Revision ID: ca945fed3446
Revises: 3be17a7deb6c
Create Date: 2025-05-12 06:26:33.431876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca945fed3446'
down_revision = '3be17a7deb6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "ck_cart_item_type",
        "cart_items",
        "(product_id IS NOT NULL AND service_id IS NULL) OR (product_id IS NULL AND service_id IS NOT NULL)"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_cart_item_type", "cart_items", type_="check")
    # ### end Alembic commands ###
